### ISSUE TITLE
Codecov says these lines are not covered by tests.

### ISSUE THREAD

**Issue by showcy** [UBC-MDS/collinearityR_tool#34]
Hi all,

When I am doing workflow stuff, I noticed Codecov says the following lines are not covered by tests which makes our coverage is staying at 95%. I am not sure if we are required to make it be 100%, if yes, you might need to add the error message in expect_error to compare the error messages. If we are not required to meet 100%, please delete this issue.

For Ana:
`
  if (!is.vector(x)) {
    stop("x must be a vector of explanatory variables!")
  }
`

For Katia:

` if (!is.numeric(corr_min)) {
         stop("corr_min should be numeric")
    }`

` if (!is.numeric(corr_max)) {
         stop("corr_max should be numeric")
    }`

`if (!is.numeric(vif_limit)) {
         stop("vif_limit should be numeric")
    }`

The full report can be found here: [https://app.codecov.io/gh/UBC-MDS/collinearityR_tool/blob/main/R/collinearityR.R](https://app.codecov.io/gh/UBC-MDS/collinearityR_tool/blob/main/R/collinearityR.R)

**Comment by katerinkus** [comment]
According to instructors, it is not necessary to get 100% code coverage so I will leave it as is.

**Comment by katerinkus** [comment]
I had a bit of time and figured it out on my end.
You can see my PR here: https://github.com/UBC-MDS/collinearityR_tool/pull/35

**Comment by Anahita97** [comment]
Just modified my code, and we are at 100% coverage!
